name: Verificação do projeto

on:
  push:
  pull_request:

jobs:
  testes:
    runs-on: ubuntu-latest
    steps:
      - name: Baixa o código
        uses: actions/checkout@v5
      - name: Configura Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - name: Instala dependências
        run: pip install -r requirements.txt
      - name: Executa testes
        run: python -m unittest discover -s testes -v
